{
'name': 'iLoda WMS APP',
'version': '1.1',
'author': 'iLoda Solutions Limited',
'summary': 'Warehouse, Stock, Barcode',
'website': 'www.ilodasolutions.com',
'depends': ['stock'],
'category': 'Warehouse Management',
'sequence': 16,
'data': ['framework_view.xml',
         'groups_view.xml',
         'ir_sequence_data.xml',
         'ir_property_data.xml',
         'res_config_view.xml',
         'taobao_view.xml',
         'license_view.xml',
         'stock_view.xml',
         ],
'installable': True,
'application': True,
}